[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
    -v 
    --strict-markers 
    --disable-warnings
    --tb=short
    --cov=src
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=80
"""
testpaths = ["tests"]
markers = [
    "unit: marca para tests unitarios",
    "integration: marca para tests de integración",
    "slow: marca para tests que tardan más de 30 segundos",
    "network: marca para tests que requieren conexión a internet",
    "database: marca para tests que usan la base de datos",
    "selenium: marca para tests que usan Selenium"
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
